# Generated by Django 4.2 on 2025-02-20 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255, unique=True)),
                ('latitud', models.DecimalField(decimal_places=12, max_digits=15)),
                ('longitud', models.DecimalField(decimal_places=12, max_digits=15)),
                ('velocidad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('satelites', models.IntegerField()),
                ('hdop', models.DecimalField(decimal_places=2, max_digits=4)),
                ('fechaHora', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
