# Generated by Django 4.2 on 2025-02-20 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicelocation',
            name='id',
        ),
        migrations.AlterField(
            model_name='devicelocation',
            name='device_id',
            field=models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
